// Code generated by goctl. DO NOT EDIT.
package types

type ResultMsg struct {
	Code   int         `json:"code"`
	Result interface{} `json:"result"`
	Msg    string      `json:"msg"`
}

type GetReq struct {
	Id       int `form:"id"`
	PageNo   int `form:"page_no"`
	PageSize int `form:"page_size"`
}

type TaskCreatReq struct {
	Url string `json:"url"`
	Tag string `json:"tag"`
}

type VideoDownloadReq struct {
	TaskInfoId string `json:"task_info_id"`
}
