version: '2.0'

#dilemma= /Users/zhengjm/volumes/dilemma
#dilemma= /app/dilemma

services:
  mysql:
    container_name: mysql
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'dilemma'
      MYSQL_PASS: 'aNXLSsZHc2bhbBmb'
    restart: always
    volumes:
      - "/app/dilemma/mysql/db:/var/lib/mysql"
      - "/app/dilemma/mysql/conf/my.cnf:/etc/my.cnf"
      - "/app/dilemma/mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
    networks:
      - mynet
  dilemma:
    container_name: dilemma
    image: "15735181677/youget:v1.0"
    volumes:
      - "/app/dilemma/dilemma:/app/dilemma/dilemma"
      - "/app/dilemma/workspace:/app/dilemma/workspace"
    ports:
      - "8081:8081"
      - "9090:9090"
    entrypoint: [ "/app/dilemma/dilemma/dilemma","-f=/app/dilemma/dilemma/etc/dilemma.json" ]
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - mynet
  dilemma-web:
    container_name: dilemma-web
    image: "nginx:latest"
    volumes:
      - "/app/dilemma/dilemma-web/dist:/app/dilemma-web/"
      - "/app/dilemma/dilemma-web/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"


networks:
  mynet:
    driver: bridge